# Environment & IO
paths:
  main_path: '/storage/group/cxs1024/default/mehdi/dam_break/scenario_groups_1'
  topo_file: 'dam_break_processed_data_bed.pt'
  input_file: 'dam_break_matthew_processed_data_input.pt'
  solution_file: 'dam_break_processed_data_solution.pt'

  mag_checkpoint: null
  global_checkpoint: null

  # mag_checkpoint: 'experiments/Hurricane_Matthew/saved_models/saved_model_Hurricane_Matthew_IG_Disable_Nx_328_Ny_164_Tin_1_Tout_88_Samp_test_mag_residual_model5_FNO_DDP_300.pth'
  # global_checkpoint: 'experiments/Hurricane_Matthew/saved_models/saved_model_Hurricane_Matthew_IG_Disable_Nx_328_Ny_164_Tin_1_Tout_88_Samp_test_coarse_FNO_DDP_300.pth'

# Experiment Metadata
experiment:
  case: 'dam_break'
  tag: 'test_mag_residual_model5_Deeper'
  training_mode: 'Stage1' # Options: Stage1, Stage2, Stage3
  enable_ig_loss: False
  save_results: True
  train_size: 100
  eval_size: 150
  seed: 42


# Global Hyperparameters
training:
  batch_size: 2
  epochs: 500
  learning_rate: 0.0001
  scheduler_step: 50
  scheduler_gamma: 0.95

# Model Architecture & Dimensions
model:
  operator_type: 'FNO' # Options: CNO, FNO, WNO, DeepONet
  nx: 328
  ny: 164
  total_steps: 49
  t_in: 1
  magnification_factor: 4

# Architecture-Specific Settings
# fno:
#   mode_x: 8
#   mode_y: 8
#   mode_t: 8
#   width: 20

fno:
  mode_x: 10
  mode_y: 10
  mode_t: 10
  width: 32

data_mask:
  mask: True
  csv_path: 'data/dam_break/DEM_data/dam_up.csv'
  L_x: 26460.0
  L_y: 20940.0
