# Environment & IO
paths:
  main_path: '/storage/group/cxs1024/default/mehdi/Hurricane_Matthew_scenario_groups/scenario_groups_1/'
  topo_file: 'hurricane_matthew_processed_data_bed_2.pt'
  input_file: 'hurricane_matthew_processed_data_input_2.pt'
  solution_file: 'hurricane_matthew_processed_data_solution_2.pt'
  global_checkpoint: 'experiments/Hurricane_Matthew/saved_models/saved_model_Hurricane_Matthew_IG_Disable_Nx_328_Ny_164_Tin_1_Tout_88_Samp_test_mag_residual_model5_Deep_FNO_DDP_300_best.pth'
  mag_checkpoint: null


# Experiment Metadata
experiment:
  case: 'Hurricane_Matthew'
  tag: 'test_mag_residual_model5_Deep_stage2_N1'
  training_mode: 'Stage2' # Options: Stage1, Stage2, Stage3
  UQ_mode: False
  enable_ig_loss: false
  save_results: True
  train_size: 300
  eval_size: 150
  seed: 42

# Global Hyperparameters
training:
  batch_size: 4  
  epochs: 500
  learning_rate: 0.0005
  scheduler_step: 50
  scheduler_gamma: 0.95

# Model Architecture & Dimensions
model:
  operator_type: 'FNO' # Options: CNO, FNO, WNO, DeepONet
  nx: 328
  ny: 164
  total_steps: 89
  t_in: 1
  magnification_factor: 4
  magnifier_window_size: 1
  WET_BATCH_QUOTA: 20
  accumulation_steps: 2

  step_time: 1
  coarsen_mode: 'bilinear'

# Architecture-Specific Settings
fno:
  mode_x: 10
  mode_y: 10
  mode_t: 10
  width: 32

data_mask:
  mask: false
  csv_path: None
  L_x: 23600.0
  L_y: 46890.0
